apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ssslf4jjp-python 
  janus-idp.io/tekton: ssslf4jjp-python
  backstage.io/kubernetes-id: ssslf4jjp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ssslf4jjp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml