apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ssslf4jjp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ssslf4jjp-python 
  name: ssslf4jjp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ssslf4jjp-python 
